import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Twitter Contest V1
        </h1>

        
        <p>Time left in contest: 11 days, 3 hours, 45min.</p>
        <p>Time left in current window: 22min!</p>
        <p>Total participants in current contest: 4.</p>
        <p>Total stakes on the line: $1785</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Register &rarr;</h2>
            <p>Enter the current contest.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Claim rewards &rarr;</h2>
            <p>Withdraw your initial stake and rewards from losers' stakes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Report loser &rarr;</h2>
            <p>If someone broke their tweeting streak.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>View contest rules &rarr;</h2>
            <p>
  
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
